version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: ["python", "analyze.py"]

  test:
    build: .
    volumes:
      - .:/app
    command: ["pytest", "tester.py"]
